 
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        name: Install Dependencies
      - run: flutter pub get
        name: format all file in the libe directory
      - run: flutter format lib
        name: Generate necessary files and delete conflicting files
      - run: flutter pub run build_runner build --delete-conflicting-outputs
        name: Analyze Code, searching for problems and errors
      - run: flutter analyze
        name: Run test written in the test folder
      - run: flutter test
        name: Build APk
      - run: flutter build apk --debug --split-per-abi
        name: Push to Releases
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
